apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ollama-bridge.fullname" . }}
  labels:
    {{- include "ollama-bridge.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ollama-bridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ollama-bridge.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: ollama-bridge
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OLLAMA_HOST
              value: "{{ .Values.env.OLLAMA_HOST }}"
            - name: MATTERMOST_URL
              value: "{{ .Values.env.MATTERMOST_URL }}"
            - name: OLLAMA_TIMEOUT
              value: "{{ .Values.env.OLLAMA_TIMEOUT }}"
            - name: MATTERMOST_BOT_TOKENS
              value: "{{ join "," .Values.botTokens }}"
            - name: OLLAMA_MODELS
              value: "{{ join "," .Values.models }}"
          ports:
            - containerPort: 8000
